[SeatDefaults]
xserver-command=X -dpi $DPI
greeter-session=lightdm-greeter
session-wrapper=/etc/X11/Xsession
display-setup-script=/usr/bin/early-bg
allow-guest=false
#autologin-user=demo
#autologin-user-timeout=0
